#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "*****Running unit tests******"

# git stash -q --keep-index

yarn run test --watchAll=false

# status=$?

# git stash pop -q

yarn run pre-commit
exit $status

